name: Daily Python Update

on:
  schedule:
    # Runs every day at 00:30 UTC
    - cron: '30 0 * * *'
  workflow_dispatch:  # lets you run it manually too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python generate_data.py

    - name: Commit and push results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Auto-update data on $(date)"
        git push
      env:
        # Required for push permissions
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
