name: Daily Python Update

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install obspy matplotlib pandas

    - name: Run Python script
      run: |
        python AfetchData.py
        python BmakeKavachiNoiseProfile.py        
        python CsaveActivityCurves.py
        python DsaveDayplots.py

    - name: Commit and push results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Auto-update data on $(date)"
        git push
      env:
        # Required for push permissions
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
